services:
  webapp:
    build:
      context: .
    container_name: webapp
    env_file:
      - ./.env
    command: /docker/webapp.sh
    ports:
      - "8000:8000"
    volumes:
      - ./:/memes_app
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: